### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### NumPy arrays are stored and processed using optimized C code, which makes them much faster than Python lists.

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# np.ones and np.zeros
np.ones((3,4)) # uses in nerral networks in weights , intitialize values

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.random
np.random.random((3,4))

array([[0.49500987, 0.30045063, 0.93040339, 0.39459367],
       [0.20931967, 0.51890567, 0.38592198, 0.18262274],
       [0.35621494, 0.29269913, 0.71239058, 0.70334164]])

In [12]:
# np.linspace  ->linspace : linear space
np.linspace(-10,10,10,dtype=int)
# np.linspace -> generate linearly separable points in a given range

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [13]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- **np.array** → create NumPy array from list or tuple  
- **arange** → generate evenly spaced values within range  
- **reshape** → change array shape (rows and columns)  
- **ones** → create array filled with ones  
- **zeros** → create array filled with zeros  
- **random** → generate array with random values  
- **linspace** → generate evenly spaced values between two numbers  
- **identity** → create identity matrix with diagonal ones  

### Array Attributes

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# ndim
a3.ndim

3

In [16]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
# itemsize
a3.itemsize

8

In [19]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


- **ndim** → returns number of dimensions of array  
**shape** → returns number of elements in each dimension of the array  
- **size** → returns total number of elements in array  
- **itemsize** → returns size of each element in bytes  
- **dtype** → returns data type of array elements  

### Changing Datatype

In [20]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Important points ⚠️**

→ `astype()` always creates a new array (original remains unchanged)  
→ conversion may cause data loss (float → int)  
→ all elements become same type after conversion  

### Array Operations

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
# scalar operations

# arithmetic -> + , - , / , *
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
# relational -> = , == , < , > , =< , => 
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [25]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array and Vector Operations (NumPy)

→ operations performed element-wise on NumPy arrays and vectors

- **Arithmetic operations** → perform +, −, ×, ÷ element-wise between arrays  
- **Scalar operations** → apply a single value to every element  
- **Comparison operations** → compare elements and return boolean values  
- **Aggregate operations** → compute summary values (sum, mean, max, min)  
- **Universal functions** → apply NumPy functions element-wise (sqrt, sin, exp)  
- **Broadcasting** → perform operations on arrays of different shapes  
- **Vector operations** → perform element-wise operations on 1D arrays (vectors)  
- **Matrix operations** → perform element-wise operations on 2D arrays  
- **Dot product** → sum of element-wise multiplication of two vectors  

### Array Functions

In [26]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[48., 87., 39.],
       [23., 68., 60.],
       [97.,  9., 24.]])

In [27]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1,axis=0)
np.prod(a1,axis=1)

array([162864.,  93840.,  20952.])

In [28]:
# mean/median/std/var
np.var(a1,axis=1)
np.mean(a1)
np.mean(a1,axis=1)

np.median(a1)
np.median(a1,axis=0)

np.std(a1)
np.std(a1,axis=1)

np.var(a1)
np.var(a1,axis=0)

array([ 944.66666667, 1102.88888889,  218.        ])

In [29]:
# trigonomoetric functions
np.sin(a1)
np.cos(a1)

array([[-0.64014434,  0.56975033,  0.26664293],
       [-0.53283302,  0.44014302, -0.95241298],
       [-0.92514754, -0.91113026,  0.42417901]])

In [30]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [31]:
# log and exponents
np.log(a1)

np.exp(a1)


array([[7.01673591e+20, 6.07603023e+37, 8.65934004e+16],
       [9.74480345e+09, 3.40427605e+29, 1.14200739e+26],
       [1.33833472e+42, 8.10308393e+03, 2.64891221e+10]])

In [32]:
# round/floor/ceil

np.random.random((2,3))*100

np.round(np.random.random((2,3))*100)

np.floor(np.random.random((2,3))*100)

np.ceil(np.random.random((2,3))*100)




array([[36., 82., 38.],
       [19., 79., 71.]])

### Array Functions (NumPy)
→ functions used to perform mathematical operations on array elements

- **sum()** → returns total of all elements in array → `np.sum(a)`
- **min()** → returns smallest element in array → `np.min(a)`
- **max()** → returns largest element in array → `np.max(a)`
- **mean()** → returns average of array elements → `np.mean(a)`
- **median()** → returns middle value after sorting → `np.median(a)`
- **std()** → returns spread of data from mean (standard deviation) → `np.std(a)`
- **var()** → returns variance of array elements → `np.var(a)`

- **sin()** → computes sine value of each element → `np.sin(a)`
- **cos()** → computes cosine value of each element → `np.cos(a)`
- **round()** → rounds elements to nearest integer → `np.round(a)`
- **ceil()** → rounds each element to next higher integer → `np.ceil(a)`
- **floor()** → rounds each element to next lower integer → `np.floor(a)`

- **log()** → returns natural logarithm (base e) of elements → `np.log(a)`
- **exp()** → returns exponential (e^x) of elements → `np.exp(a)`

- **dot()** → returns sum of element-wise multiplication of two arrays → `np.dot(a, b)`

### Indexing and Slicing

#### Indexing
Indexing is the process of accessing a specific element of an array using its position (index).

In [33]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1[-1]
a1[-4]
a1[3]

np.int64(3)

In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a2[1,0]

# 10
a2[2,2]

#4
a2[1,0]

np.int64(4)

In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
a3[1,0,1]

# 3
a3[0,1,0]
# 0
a3[0,0,0]
#
7
a3[1,1,1]

np.int64(7)

In [40]:
a3[1,1,0]

np.int64(6)

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### NumPy Indexing (Common Patterns)

`a[0]`      → first element  
`a[1]`      → second element  
`a[-1]`     → last element  
`a[-2]`     → second last element  

`a[0,0]`    → first row, first column (2D)  
`a[0,1]`    → first row, second column  
`a[1,0]`    → second row, first column  
`a[1,1]`    → second row, second column  

`a[0,1,0]`  → depth 0, row 1, column 0 (3D)  
`a[1,0,1]`  → depth 1, row 0, column 1 (3D)  

`a[0,:]`    → first row (2D indexing)  
`a[:,0]`    → first column (2D indexing)  
`a[-1,:]`   → last row  
`a[:,-1]`   → last column  

#### Slicing
Slicing is the process of extracting a portion (subset) of elements from a NumPy array using index range.<br>
Slicing is used to select a range of elements from an array.

In [42]:
a1[2:5]

a1[2:5:2]



array([2, 4])

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2[0,:] # gives paticular row

array([0, 1, 2, 3])

In [45]:
a2[:,2] # gives paticular column

array([ 2,  6, 10])

In [46]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [47]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [48]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [49]:
a2[1,::3]

array([4, 7])

In [50]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [51]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [52]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [53]:
a2[1,::3]

array([4, 7])

In [54]:
a2[0,:]

array([0, 1, 2, 3])

In [55]:
a2[:,2]

array([ 2,  6, 10])

In [56]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [59]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
a3[::2,0,::2]
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
a3[0,1,:]

array([3, 4, 5])

In [62]:
a3[1,:,1]

array([10, 13, 16])

In [63]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [64]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [65]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [66]:
a3[0,1,:]

array([3, 4, 5])

### Indexing and Slicing (NumPy)
→ methods used to access single or multiple elements from an array

### Indexing
→ accessing individual element using its position (index)

- **1D indexing** → access element using single index → `a[0]`
- **2D indexing** → access element using row and column index → `a[1,2]`
- **Negative indexing** → access elements from end of array → `a[-1]`

### Slicing
→ extracting a subset of array using range of indices

- **1D slicing** → select elements using start:end → `a[1:4]`
- **Step slicing** → select elements with step size → `a[0:5:2]`
- **2D slicing (rows)** → select rows → `a[0:2, :]`
- **2D slicing (columns)** → select columns → `a[:, 1:3]`
- **Row and column slicing** → select submatrix → `a[0:2, 1:3]`

### NumPy Slicing (Common Patterns)

`a[1:4]`   → elements from index 1 to 3  
`a[:3]`    → first three elements  
`a[::2]`   → every second element  
`a[:,1]`   → full column (2D)  

`a[2:]`    → from index 2 to end  
`a[:-1]`   → all except last element  
`a[-3:]`   → last three elements  
`a[::-1]`  → reverse array  

`a[1:5:2]` → elements from index 1 to 4 with step 2  
`a[:]`     → entire array  
`a[::]`    → entire array (same)  

`a[0,:]`   → first row (2D)  
`a[1,:]`   → second row (2D)  
`a[:,:]`   → full 2D array  
`a[0:2,:]` → first two rows  
`a[:,0:2]` → first two columns  

`a[1:3,1:3]` → middle sub-matrix  
`a[:,-1]`    → last column  
`a[-1,:]`    → last row  

### Iterating

In [67]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
for i in a2: # in one time one row is printed
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [70]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
for i in a3:  # in one time one 2D matrix is printed
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [72]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### NumPy Iterating

**Definition:**  
Iterating means accessing array elements one by one.

`for x in a`  
→ iterate through 1D array elements  

`for row in a`  
→ iterate row by row (2D array)  

`for row in a:`  
`    for element in row`  
→ iterate each element in 2D array  

`np.nditer(a)`  
→ iterate all elements (any dimension)  

`np.ndenumerate(a)`  
→ iterate with index and value  

`a.flatten()`  
→ convert to 1D then iterate easily  

**Notes**
- Used to access elements one by one  
- `nditer()` best for multi-dimensional arrays  
- `ndenumerate()` gives index + value  
- Vectorized operations are faster than loops

### Reshaping

In [73]:
# reshape

In [74]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [75]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

### NumPy Stacking

**Definition:**  
Stacking means joining two or more arrays together.

**Syntax**
`np.vstack((a,b))` → stack vertically (row-wise)  
`np.hstack((a,b))` → stack horizontally (column-wise)  
`np.stack((a,b), axis=0)` → stack along new axis  

**Explanation**
`vstack` → arrays placed one below another  
`hstack` → arrays placed side by side  
`stack`  → creates new dimension  

**Note**
- Arrays should have same shape  
- Returns new array  
- Original arrays are not changed

In [76]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [78]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

### NumPy Splitting

**Definition:**  
Splitting means dividing an array into multiple smaller arrays.

**Syntax**
`np.split(a, sections)`      → split into equal parts  
`np.hsplit(a, sections)`     → split horizontally (column-wise)  
`np.vsplit(a, sections)`     → split vertically (row-wise)  
`np.array_split(a, sections)` → split (equal or unequal)

**Explanation**
`split`        → divides array into equal parts  
`hsplit`       → split by columns  
`vsplit`       → split by rows  
`array_split`  → allows unequal splits  

**Note**
- Returns multiple arrays  
- Original array not changed  
- Used to divide dataset

In [79]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,2)

ValueError: ignored